version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
  
  person_service:
    container_name: person_service
    build:
      context: src/PersonService
      dockerfile: PersonService.Server/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    

volumes:
  db-data: